baseURL = 'https://guide.jiangliuhong.top/'
languageCode = 'zh-cn'
title = '复习吧'
theme = 'hugo-book'
enableGitInfo = true
[params]
BookTheme = 'auto'
BookToC = true
BookMenuBundle = '/menu'
BookSection = 'docs'
BookSearch = true
BookTranslatedOnly = true
[markup.tableOfContents]
  startLevel = 2
  endLevel = 6